name: Release version

on:
    push:
        branches:
            - dev

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Ensure full history for correct versioning

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21

            - name: Install dependencies (frontend)
              run: npm ci
              working-directory: ./frontend

            - name: Install dependencies (backend)
              run: npm ci
              working-directory: ./backend

            - name: Run Semantic Release (frontend)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
              working-directory: ./frontend

            - name: Run Semantic Release (backend)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
              working-directory: ./backend
